<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="93b45e58-5997-4adc-a3a1-07b05301214d" name="Truong Tho@TRUONGTHO-PC 2012-05-17 23:43:06" runUser="TruongTho-PC\Truong Tho" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="0210f5e3-9eec-4396-b5fb-9dc61770bc14">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Truong Tho_TRUONGTHO-PC 2012-05-17 23_43_06">
      <DeploymentItem filename="F:\Workplace\WPF-WCF\SourceProject\kyan-projects\DemoRalcon\DemoRalcon\bin\Debug\DemoRalcon.exe" />
      <DeploymentItem filename="C:\Program Files (x86)\System.Data.SQLite\2010\bin\System.Data.SQLite.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2012-05-17T23:43:06.7001371+07:00" queuing="2012-05-17T23:43:06.7481399+07:00" start="2012-05-17T23:43:06.7541402+07:00" finish="2012-05-17T23:43:07.2101663+07:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="GetAllTest" storage="f:\workplace\wpf-wcf\sourceproject\kyan-projects\demoralcon\dataaccesstest\bin\debug\dataaccesstest.dll" id="92a7d1f2-e424-0bb4-2265-fdec17dd5cf2">
      <Execution id="e52de9b5-b7ee-43c9-8534-473677039b63" />
      <TestMethod codeBase="F:/Workplace/WPF-WCF/SourceProject/kyan-projects/DemoRalcon/DataAccessTest/bin/Debug/DataAccessTest.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="DataAccessTest.EmployeeDataAccessTest, DataAccessTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="GetAllTest" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="92a7d1f2-e424-0bb4-2265-fdec17dd5cf2" executionId="e52de9b5-b7ee-43c9-8534-473677039b63" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="e52de9b5-b7ee-43c9-8534-473677039b63" testId="92a7d1f2-e424-0bb4-2265-fdec17dd5cf2" testName="GetAllTest" computerName="TRUONGTHO-PC" duration="00:00:00.1234820" startTime="2012-05-17T23:43:06.7651408+07:00" endTime="2012-05-17T23:43:07.1891651+07:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="e52de9b5-b7ee-43c9-8534-473677039b63">
      <Output>
        <DebugTrace>
|| === Exception === 
|| Source :System.Data.SQLite
|| Message :SQLite error
no such table: Employees
|| StackTrace :   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String&amp; strRemain) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLite3.cs:line 476
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand() in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteCommand.cs:line 294
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteCommand.cs:line 301
   at System.Data.SQLite.SQLiteDataReader.NextResult() in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteDataReader.cs:line 1146
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteDataReader.cs:line 103
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteCommand.cs:line 592
   at System.Data.SQLite.SQLiteCommand.ExecuteReader() in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteCommand.cs:line 604
   at DemoFalcon.DataAccess.EmployeeDataAccess.GetAll() in F:\Workplace\WPF-WCF\SourceProject\kyan-projects\DemoRalcon\DemoRalcon\DataAccess\EmployeeDataAccess.cs:line 76
|| TargetSite :System.Data.SQLite.SQLiteStatement Prepare(System.Data.SQLite.SQLiteConnection, System.String, System.Data.SQLite.SQLiteStatement, UInt32, System.String ByRef)
|| Data :
|| All :System.Data.SQLite.SQLiteException (0x80004005): SQLite error
||no such table: Employees
||   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String&amp; strRemain) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLite3.cs:line 476
||   at System.Data.SQLite.SQLiteCommand.BuildNextCommand() in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteCommand.cs:line 294
||   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteCommand.cs:line 301
||   at System.Data.SQLite.SQLiteDataReader.NextResult() in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteDataReader.cs:line 1146
||   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteDataReader.cs:line 103
||   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteCommand.cs:line 592
||   at System.Data.SQLite.SQLiteCommand.ExecuteReader() in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteCommand.cs:line 604
||   at DemoFalcon.DataAccess.EmployeeDataAccess.GetAll() in F:\Workplace\WPF-WCF\SourceProject\kyan-projects\DemoRalcon\DemoRalcon\DataAccess\EmployeeDataAccess.cs:line 76
|| Data System.Collections.ListDictionaryInternal
</DebugTrace>
        <ErrorInfo>
          <Message>Test method DataAccessTest.EmployeeDataAccessTest.GetAllTest threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.</Message>
          <StackTrace>    at DemoFalcon.DataAccess.EmployeeDataAccess.GetAll() in F:\Workplace\WPF-WCF\SourceProject\kyan-projects\DemoRalcon\DemoRalcon\DataAccess\EmployeeDataAccess.cs:line 93
   at DataAccessTest.EmployeeDataAccessTest.GetAllTest() in F:\Workplace\WPF-WCF\SourceProject\kyan-projects\DemoRalcon\DataAccessTest\EmployeeDataAccessTest.cs:line 119
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>